### PR TITLE
[feature #158422833] joined and offered rides

### PR DESCRIPTION
**Pull request by TheSteelGuy**
**Introduction**
This PR creates a profile page where a user can see all the rides they have offered and or been offered
**Description of Task completed:**

- Two separate tables each with 4 columns.
- The columns are last stop, time of departure, meeting point and charges

How to manually test

**Clone this repository**

navigate into the repository after cloning
navigate further in the UI directory open the profile.html page with a browser

**Screenshots**

prof
**Changes incorporated**
profile

### CODE REVIEW

**Comment by kwanj-k** [comment]
Cool UI,but your navigation links are not very visible due to the background,you could try a different color on the links maybe

**Comment by meshack-mbuvi** [comment]
Make a point of having a different background-color for navigation bar so that your links are visible

**Comment by TheSteelGuy** [comment]
Nice nice

**Comment by TheSteelGuy** [comment]
Changes have been made through it will be available on my next commit

**Pull request merged**
